```{r}
library(exams)
library(ggplot2)

# Generate plots to illustrate violations of assumptions
violation_types <- sample(c(TRUE, FALSE), 2, replace = TRUE, prob = c(0.33, 0.67))
x = runif(100, 0, 100)
y = 3 * x + 23.2 + rnorm(100, mean = 0, sd = 2)
plot_data <- data.frame(x = x, y = y)

# Introduce violations based on selected types
if (violation_types[1]) {
  plot_data$y <- plot_data$y + 25 * (plot_data$x)^2  # Introduce non-linearity
}

if (violation_types[2]) {
  plot_data$y <- plot_data$y + rnorm(100, sd = plot_data$x * 250)  # Introduce heteroscedasticity
}

# Plot the data with possible violations
scatter_plot <- ggplot(plot_data, aes(x = x, y = y)) +
  geom_point() +
  geom_smooth(method = "lm", formula= y~x, se = FALSE, color = "red") +
  ggtitle("Scatter Plot with Violations of Assumptions")

qq_plot <- ggplot(plot_data, aes(sample = y)) +
  stat_qq() +
  stat_qq_line(color = "red") +
  ggtitle("Q-Q Plot for Normality Check")

residuals <- resid(lm(y ~ x, data = plot_data))
residual_plot <- ggplot(data = plot_data, aes(x = x, y = residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  ggtitle("Residual Plot for Checking Homoscedasticity") +
  ylab("Residuals")



# Define the question list and answers
questions <- c(
  "Homoscedasticity (equal variance):",
  "Linearity:",
  "None of the above assumptions are violated."
)

solutions <- c(
  violation_types[2],
  violation_types[1],
  !any(violation_types)
)

explanations <- c(
  ifelse(violation_types[2], "There is evidence of heteroscedasticity, as the variance of residuals changes with predictors.", "Residuals appear to have equal variance (homoscedasticity)."),
  ifelse(violation_types[1], "The relationship between predictors and outcome does not appear to be linear.", "The relationship between predictors and outcome appears to be linear."),
  ifelse(!any(violation_types), "None of the assumptions are visibly violated.", "At least one assumption is violated.")
)

# Randomize order of questions
Order <- sample(1:3)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]
```

Question
========

Use the graphs to check the following boxes as appropriate:
```{r plots}

print(scatter_plot)
print(qq_plot)
print(residual_plot)
```


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: mchoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice Assumptions